add zap metadata
NYCPlanning/product-metadata pull request #3
Opened 2024-06-20 20:25 UTC by damonmcc

2024-06-21 16:29 UTC, alexrichey commented on products/zap/bbls/metadata.yml
> +description: "The Department of City Planning (DCP) processes land use applications\
@damonmcc Let's format the long lines with nice yaml style. [this](https://stackoverflow.com/questions/3790454/how-do-i-break-a-string-in-yaml-over-multiple-lines) might be helpful. 

TLDR: remove carriage-returns and newlines, `\u2019` chars, and backslashes. Also, we should just remove the summary from our models. I can't remember quite what it was for, but it's not used, and now just an annoyance.

2024-06-21 16:32 UTC, alexrichey requested changes
Looks good! Let's clean up the descriptions while we're here, then 👍

2024-06-26 15:35 UTC, damonmcc commented
@alexrichey
> Looks good! Let's clean up the descriptions while we're here, then 👍

see [fdcf5bd](https://github.com/NYCPlanning/product-metadata/pull/3/commits/fdcf5bdce5a060424fbc4e01aec2278b590064ce)

2024-06-26 15:38 UTC, alexrichey approved these changes
Cool - FYI, can add the xlsx's back

2024-06-26 16:22 UTC, merged